version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - SOCKS_ADDRESS=0.0.0.0:1080
    depends_on:
      - redis
    ports:
      - "1080:1080"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: